Vagrant.configure("2") do |config|
    # Box configuration
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_check_update = false
    config.vm.hostname = 'weemaps.com'

    # VirtualBox runtime parameters
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 3000 #MB
        vb.cpus = 2
    end

    # Use host directory
    config.vm.synced_folder ".", "/box_config/"

    # Create a private network, which allows host-only access to the machine using a specific IP address.
    config.vm.network "private_network", ip: "192.168.33.101"

    # Configure 'vagrant-hostmanager' plugin or display warning message and instructions.
    # The plugin will manage system host file so that we can use http://weemaps.com instead of box ip address.
    if Vagrant.has_plugin?("vagrant-hostmanager")
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.manage_guest = false
        config.hostmanager.ignore_private_ip = false
        config.hostmanager.include_offline = true
    else
        warn <<-HOST_MANAGER_NOT_INSTALLED
        WARNING!
        Plugin vagrant-hostmanager is not installed. It's goal is to manage host files on host and guest machines.

        Install the plugin:
        vagrant plugin install vagrant-hostmanager

        Alternatively, manually add the following line to the system host file:
        192.168.33.101  weemaps.com

        linux, mac: /etc/hosts
        windows:    C:\Windows\System32\drivers\etc

        Plugin site: https://github.com/devopsgroup-io/vagrant-hostmanager

        HOST_MANAGER_NOT_INSTALLED
   end

    # Use shell scripts to provision the machine
    %w[java utilities elasticsearch mongodb nginx].each do |script|
        config.vm.provision "shell", path: "install_scripts/#{script}.sh"
    end
end
